dist: trusty
sudo: required

language: python
python:
  - "3.6"

# command to install dependencies
install: 
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n adain python=3.6 anaconda=5.1.0
  - source activate adain
  - pip install tensorflow==1.9.0
  - pip install opencv-python==3.4.3.18
  - pip install pytest-cov
  - pip install codecov
  - pip install -e .

# command to run tests
script: pytest -x --cov=adain tests

#Upload code coverage statistics
after_success:
  - codecov